baseURL = "https://pedrojunqueira.github.io/blog"
languageCode = "en-us"
title = "Pedro Junqueira Site"

theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Pedro Junqueira"
    subtitle = ""
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "home/pedrojunqueira: ~$"
      logoHomeLink = "/blog"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    # Social icons
   [[params.social]]
     name = "twitter"
     url  = "https://twitter.com/"

   [[params.social]]
     name = "email"
     url  = "mailto:nobody@example.com"

   [[params.social]]
     name = "github"
     url  = "https://github.com/"

   [[params.social]]
     name = "linkedin"
     url  = "https://www.linkedin.com/"

   [[params.social]]
     name = "stackoverflow"
     url  = "https://www.stackoverflow.com/"

  # And you can even create generic menu
  [menu]
  [[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
